/**
 * Responsive sources for the character artwork.
 *
 * `imageManifest.json` is generated by `npm run images` from whatever PNGs are
 * sitting in public/assets/characters/. A character with no manifest entry —
 * because the file was just dropped in, or sharp was unavailable — simply
 * falls back to its original PNG. Nothing breaks.
 */

import manifest from '../data/imageManifest.json';

interface ManifestEntry {
  width: number;
  height: number;
  sources: { width: number; src: string }[];
}

const entries = manifest as Record<string, ManifestEntry>;

export interface ArtworkSources {
  /** Original PNG — the <img> fallback, and what you replace to swap artwork. */
  png: string;
  /** WebP srcset, or undefined when no derivatives exist. */
  webpSrcSet?: string;
  /** Intrinsic dimensions, used to reserve space and avoid layout shift. */
  width?: number;
  height?: number;
}

export function getArtworkSources(pngPath: string): ArtworkSources {
  const entry = entries[pngPath];
  if (!entry || entry.sources.length === 0) return { png: pngPath };

  return {
    png: pngPath,
    webpSrcSet: entry.sources.map((s) => `${s.src} ${s.width}w`).join(', '),
    width: entry.width,
    height: entry.height,
  };
}

/** The smallest derivative — good enough for <link rel="preload"> on the cover. */
export function getPreloadSource(pngPath: string): string {
  const entry = entries[pngPath];
  return entry?.sources[1]?.src ?? entry?.sources[0]?.src ?? pngPath;
}
